language: generic
sudo: required

services:
    - docker
before_install:
    - docker build -t vikramjadhav/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true vikramjadhav/react-test npm test
after_success:
    - docker build -t vikramjadhav/multi-client ./client
    - docker build -t vikramjadhav/multi-nginx ./nginx
    - docker build -t vikramjadhav/multi-server ./server
    - docker build -t vikramjadhav/multi-worker ./worker
    
    # Login to dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push above crated images
    - docker push vikramjadhav/multi-client
    - docker push vikramjadhav/multi-nginx
    - docker push vikramjadhav/multi-server
    - docker push vikramjadhav/multi-worker

